### ISSUE TITLE
示例代码报错

### ISSUE THREAD

**Issue by XIAOGUIGUI** [easy-team/ves#2]
![1551105316832](https://user-images.githubusercontent.com/8243283/53344478-bc8af880-394d-11e9-807f-6854f40b2229.jpg)

**Comment by XIAOGUIGUI** [comment]
babel插件添加多babel-plugin-dynamic-import-webpack

**Comment by hubcarl** [comment]
@XIAOGUIGUI  骨架是没有问题，你那是报错刚好是遇到 webpack 更新的一个版本导致，现在没有问题了
