### ISSUE TITLE
ves 和 egg-vue 的差异是什么

### ISSUE THREAD

**Issue by usherwong** [easy-team/ves#3]
看了官网，想了解下和隔壁Egg-vue的差异是什么呢，什么时候适用ves。
看文档都是基于Egg+Vue 支持SSR和CSR都支持TS，JS。
想了解下他们的差异，以及适用情况，谢谢

**Comment by hubcarl** [comment]
@usherwong  ves 是把 egg, vue, webpack 封装成框架了，本质没有区别。
